dist: bionic  # Ubuntu 18.04

language: python

sudo: required

matrix:
  include:
    #- python: 2.7
    #  dist: xenial  # Ubuntu 16.04
    #  env: TOXENV=py27
    - python: 3.5
      dist: xenial  # Ubuntu 16.04
      env: TF_VERSION="tensorflow<2.0"
    - python: 3.6
      dist: bionic  # Ubuntu 18.04
      env: TF_VERSION="tensorflow<2.0"
    - python: 3.7
      dist: bionic  # Ubuntu 18.04
      env: TF_VERSION="tensorflow<2.0"
    - python: 3.6
      dist: bionic  # Ubuntu 18.04
      env: TF_VERSION="tensorflow>=2.0"
    - python: 3.7
      dist: bionic  # Ubuntu 18.04
      env: TF_VERSION="tensorflow>=2.0"

cache: pip

install:
    # see: https://github.com/fizyr/keras-retinanet/issues/1123#issuecomment-541566486
    - pip install $TF_VERSION
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - pip list

script:
    - python setup.py check -m -s
    - python setup.py build_ext --inplace
    - python setup.py install --dry-run
    - coverage run --source keras_retinanet -m py.test keras_retinanet tests --doctest-modules --forked --flake8

after_success:
    - coverage xml
    - coverage report
    - codecov
