dist: bionic  # Ubuntu 18.04

language: python

sudo: required

python:
    - '2.7'
    - '3.5'
    - '3.6'
    - '3.7'

install:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt

cache: pip

script:
    - python setup.py check -m -s
    - python setup.py build_ext --inplace
    - python setup.py install --dry-run
    - coverage run --source keras_retinanet -m py.test keras_retinanet tests --doctest-modules --forked --flake8 --ignore=tests/models/test_densenet.py --ignore=tests/models/test_mobilenet.py

after_success:
    - coverage xml
    - coverage report
    - codecov
