dist: bionic  # Ubuntu 18.04

language: python

sudo: required

python:
    - '2.7'
    - '3.5'
    - '3.6'
    - '3.7'

cache: pip

install:
    # see: https://github.com/fizyr/keras-retinanet/issues/1123#issuecomment-541566486
    # - pip install "tensorflow<2.0"
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt

script:
    - python setup.py check -m -s
    - python setup.py build_ext --inplace
    - python setup.py install --dry-run
    - coverage run --source keras_retinanet -m py.test keras_retinanet tests --doctest-modules --forked --flake8

after_success:
    - coverage xml
    - coverage report
    - codecov
